name: Deploy Site
on:
  push:
    branches:
      - main
jobs:
  update-s3:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload page
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: laboratory-ci-cd
          AWS_ACESS_KEY_ID: ${{secrets.AWS_ACESS_KEY_ID}}
          AWS_SECRET_ACESS_KEY: ${{secrets.AWS_SECRET_ACESS_KEY}}
